### PR TITLE
Milestone #1 Diagram

### PR DESCRIPTION
**Pull request by denisdiaconu**
We created the database model by using the Entity Relationship Diagram and inside it, we have the following models:
-  Users
- Friends
- Friendship
- Posts
- Comments
- Likes

### CODE REVIEW

**Review by MahmoudBakr23 — COMMENTED** [review]
# **Invalid ⚠️**

<hr>

hello there 🙂 
Please setup your Linter in order to get your PR reviewed 😊🙏

Good luck and happy coding 👍🏻

**Review by cyonii — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️✍️

Hello team, this is a great start, please take a look at the review below and fix these issues before resubmitting for review.

## To Improve
> Your ERD should look similar to [this image](https://gitlab.com/microverse/guides/tse/code_review/code_review_guidelines/-/raw/master/images/rails/final_project/erd.png)
- [x] The table names in your ERD have been pluralized, by standard they should be singular.  
- [x] You have not illustrated the relationship between your `Like` table and `Post` table.
- [x] You have not illustrated the relationship between your `Comment` table and `Post` table.
- [x] There should be no `Friends` table in the ERD
- [x] Ensure you use the correct endpoints to illustrate the relationship between your tables.
- [x] Ensure you correctly assign the Primary Keys (PK) and Foreign Keys (FK) 


## Nice to have
Note that these are my suggestions, although you are not obliged to implement them but I recommend that you do.
- [x] [OPTIONAL] The text on the far right of your ERD screenshot is a bit distracting, you may want to crop it.
- [x] [OPTIONAL] It'd be nice to specify the data types of your table rows.


Keep up the energy, happy coding. 🤓💻

> #### <br>You can ping me on Slack @[CY Kalu](https://microverse-students.slack.com/team/U01494U96FR) to draw my attention in case I do not respond quickly on here. I'm always available and will be glad to help.<br><br>

**Comment by cyonii** [comment]
[Lucidchart](http://lucidchart.com) is a good tool for ERD

**Comment by billodiallo** [comment]
Hello,
Thanks for that but we are using it.what is your feedback about the changes

**Comment by cyonii** [comment]
Oh great. The next Reviewer will offer that feedback, I hope that'd me 🙃

**Review by acushlakoncept — APPROVED** [review]
# Status: PROJECT APPROVED  🎉 🚀

### Hi, @denisdiaconu and @billodiallo,  congratulations on completing this milestone and taking the time to implement the changes requested by the previous TSE.  

The Entity Relationship Diagram satisfies the requirements for this milestone 👏 

I will go ahead and mark this as complete, note the changes below and feel free to merge when you are ready. All the best with the next milestone.

* Having the table relationship line cross another table shows a bad presentation and can obstruct clarity and readability. 
* The line connecting user and post has quite an appropriate thickness that others should use.
*  Speaking of readability, in the User table, one could barely identify the name as User, you can push down a bit to fit the canvas.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Pull request merged**
