### PR TITLE
Milestone3

### PR DESCRIPTION
**Pull request by billodiallo**
-  implement friendships with 2 rows for mutual friendship.
- Add integration tests to our project.
- Add bootstrap
- Fix rubocop errors
- completed all change requested
- implement friend request properly

### CODE REVIEW

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Denis Diaconu & Billo Diallo** 
Good job with your first submission for this project :muscle:  :muscle:
We still need to fix some issues before you can go ahead:

- [x] Add integration tests to your project.
- [x] Friendship request isn't working.
- [x] Friendship model should have a method to create a second record when a friendship is confirmed.
- [x] User model should have a "has_many confirmed_friendships" and a "has_many friends".
- [x] Don't edit rubocop config file.
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @billodiallo 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes  👇.
- [x] Friendship accept functionality is working in the project. please implement it properly
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by billodiallo** [comment]
Hello TSEs
change request done.
thanks for the review.
Best regards,

**Comment by mimipeshy** [comment]
## STATUS: CHANGES REQUESTED 🔴 ♻️ 
Hello @billodiallo and @denisdiaconu 👋🏾 congratulations on making it this far in your project. Good job on implementing the TSE feedback that you have been given 😄 . However, before approval, the `friendship` model is still not working as expected. I will play the scenario for you down below
This is how your app works ⬇️ 
- [ ] I have successfully signed in to your social app and I can see a list of friends I want to send a request to. So I send a request to user A. 
- [ ] User A signs in and can see my friendship request and accepts it. However, when User A clicks accept,  your app sends me another friend request. So I have to accept User A friendship request for me to see their posts. Do you see anything wrong with the logic?

This is how it should work ⬇️ 

- [ ] Once User A accepts my request, the friendship status should be updated on both sides and we can see each other's posts without having to send a second friend request. Think of the app like Facebook friend requests and how they work.


That's all :smile: kindly submit another review when done.
_Feel free to reach out to me on slack if you have any questions or something is unclear, or just comment on this PR and tag my name  (@mimipeshy) and I will be glad to help_
Regards
Peris Ndanu

**Comment by mimipeshy** [comment]
## STATUS: APPROVED 🥳 👍🏾 
Hello, team @billodiallo and @denisdiaconu 👋🏾 👋🏾 congratulations on making the requested changes. The friendship model is no longer sending a second request to users 😄 . With that I approve of this milestone, go ahead and merge. All the best in the next milestones.


Regards
Peris Ndanu

**Pull request merged**
